[2024-05-29T00:31:45.697+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T00:31:45.734+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T09:25:00+00:00 [queued]>
[2024-05-29T00:31:45.746+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T09:25:00+00:00 [queued]>
[2024-05-29T00:31:45.747+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T00:31:45.764+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-17 09:25:00+00:00
[2024-05-29T00:31:45.771+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=370) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T00:31:45.773+0000] {standard_task_runner.py:63} INFO - Started process 389 to run task
[2024-05-29T00:31:45.774+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-17T09:25:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmp4uhx7a8l']
[2024-05-29T00:31:45.775+0000] {standard_task_runner.py:91} INFO - Job 183: Subtask criar_pasta
[2024-05-29T00:31:45.839+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T09:25:00+00:00 [running]> on host 0473b835f7f4
[2024-05-29T00:31:45.986+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T09:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T09:25:00+00:00'
[2024-05-29T00:31:45.991+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T00:31:45.993+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T00:31:45.996+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather/custom_dags/dados_climaticos_estruturados.py", line 18, in pegar_data_e_criar_pasta
    Path(caminho).mkdir(parents=True, exist_ok=True)
    ^^^^
NameError: name 'Path' is not defined
[2024-05-29T00:31:46.021+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-17T09:25:00+00:00, execution_date=20240517T092500, start_date=20240529T003145, end_date=20240529T003146
[2024-05-29T00:31:46.049+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 183 for task criar_pasta (name 'Path' is not defined; 389)
[2024-05-29T00:31:46.078+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-29T00:31:46.111+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-29T00:31:46.119+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-29T01:43:26.906+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T01:43:26.963+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T09:25:00+00:00 [queued]>
[2024-05-29T01:43:26.996+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T09:25:00+00:00 [queued]>
[2024-05-29T01:43:27.005+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T01:43:27.042+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-17 09:25:00+00:00
[2024-05-29T01:43:27.061+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=497) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T01:43:27.066+0000] {standard_task_runner.py:63} INFO - Started process 520 to run task
[2024-05-29T01:43:27.074+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-17T09:25:00+00:00', '--job-id', '287', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmp0jogqu7e']
[2024-05-29T01:43:27.081+0000] {standard_task_runner.py:91} INFO - Job 287: Subtask criar_pasta
[2024-05-29T01:43:27.240+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T09:25:00+00:00 [running]> on host 6665b0710315
[2024-05-29T01:43:27.499+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T09:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T09:25:00+00:00'
[2024-05-29T01:43:27.503+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T01:43:27.509+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-29T01:43:27.512+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T01:43:27.556+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-17T09:25:00+00:00, execution_date=20240517T092500, start_date=20240529T014326, end_date=20240529T014327
[2024-05-29T01:43:27.675+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T01:43:27.750+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-29T01:43:27.760+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
