[2024-05-25T19:05:21.548+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T19:05:21.595+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T01:40:00+00:00 [queued]>
[2024-05-25T19:05:21.615+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T01:40:00+00:00 [queued]>
[2024-05-25T19:05:21.616+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-25T19:05:21.852+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-17 01:40:00+00:00
[2024-05-25T19:05:21.868+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=228) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T19:05:21.870+0000] {standard_task_runner.py:63} INFO - Started process 245 to run task
[2024-05-25T19:05:21.871+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-17T01:40:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmpznqrr9ri']
[2024-05-25T19:05:21.873+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask criar_pasta
[2024-05-25T19:05:21.968+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T01:40:00+00:00 [running]> on host 0473b835f7f4
[2024-05-25T19:05:22.092+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T01:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T01:40:00+00:00'
[2024-05-25T19:05:22.096+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T19:05:22.097+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T19:05:22.099+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather/custom_dags/dados_climaticos_estruturados.py", line 18, in pegar_data_e_criar_pasta
    Path(caminho).mkdir(parents=True, exist_ok=True)
    ^^^^
NameError: name 'Path' is not defined
[2024-05-25T19:05:22.117+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-17T01:40:00+00:00, execution_date=20240517T014000, start_date=20240525T190521, end_date=20240525T190522
[2024-05-25T19:05:22.142+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task criar_pasta (name 'Path' is not defined; 245)
[2024-05-25T19:05:22.180+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T19:05:22.211+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T19:05:22.221+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-29T01:36:02.898+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T01:36:03.075+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T01:40:00+00:00 [queued]>
[2024-05-29T01:36:03.101+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T01:40:00+00:00 [queued]>
[2024-05-29T01:36:03.102+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T01:36:03.435+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): criar_pasta> on 2024-05-17 01:40:00+00:00
[2024-05-29T01:36:03.463+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=376) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T01:36:03.479+0000] {standard_task_runner.py:63} INFO - Started process 395 to run task
[2024-05-29T01:36:03.476+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'criar_pasta', 'scheduled__2024-05-17T01:40:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmpznsv5_yz']
[2024-05-29T01:36:03.486+0000] {standard_task_runner.py:91} INFO - Job 102: Subtask criar_pasta
[2024-05-29T01:36:03.823+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.criar_pasta scheduled__2024-05-17T01:40:00+00:00 [running]> on host dd333ca35f8c
[2024-05-29T01:36:04.241+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='criar_pasta' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T01:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T01:40:00+00:00'
[2024-05-29T01:36:04.249+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T01:36:04.259+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-29T01:36:04.264+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T01:36:04.304+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dados_climaticos_estruturados, task_id=criar_pasta, run_id=scheduled__2024-05-17T01:40:00+00:00, execution_date=20240517T014000, start_date=20240529T013603, end_date=20240529T013604
[2024-05-29T01:36:04.387+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T01:36:04.482+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-29T01:36:04.495+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
